name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t shadhirshaz/node-hello .
      - name: Publish image to docker hub
        run: docker push shadhirshaz/node-hello:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest # Use GitHub-hosted runner
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@EC2_PUBLIC_IP "
            echo 'Pull image from docker hub'
            docker pull shadhirshaz/node-hello:latest

            echo 'Delete old container'
            docker rm -f node-hello-container || true

            echo 'Run docker container'
            docker run -d -p 3000:3000 --name node-hello-container shadhirshaz/node-hello

            echo 'Waiting for container to start...'
            sleep 5

            echo 'Health check...'
            if curl -f http://localhost:3000; then
              echo 'Deployment successful!'
            else
              echo 'Deployment failed!'
              exit 1
            fi
          "
